### ISSUE TITLE
released rocon robot apps and android apps don't work with each other any more

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#101]
The ROCON Android apps, i.e talker and listener expect the topics to be namespaced following the `/<robot_name>/application/` naming scheme. However, the robot apps are now publishing under `/<robot_name>/`.

I'm tested the Hydro version of the Android apps together with the rocon_app_manager and rocon_apps both of version 0.6.1.

**Comment by bit-pirate** [comment]
The root cause for this issue might be #103.

**Comment by stonier** [comment]
Logic bug - see #103. They probably fail if hardcoded to look for application namespace and auto-invite is not on. Could fix this in android_remocons, but it will go away with hydro and no non-turtlebot users yet so won't worry unless someone from outside complains.

**Comment by stonier** [comment]
For posterity, [this](https://github.com/rosjava/android_apps/blob/hydro/application_management/src/main/java/com/github/rosjava/android_apps/application_management/rapp_manager/InvitationServiceClient.java#L113) is where we would have to bugfix hydro...and then rebuild remocon and apps.
