### ISSUE TITLE
Auto-invite causes warning

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#102]
Setting "auto-invite" to true for the public master, leads to the following warning when connecting to the robot:

```
[WARN] [WallTime: 1384773594.316760] App Manager : bastards are sending us repeat invites, so we ignore - we are already working for them! [Public Gateway86e96cca25e44b4b8024574401cb31e8]
```

Not sure, if this is intended behaviour.

**Comment by stonier** [comment]
The warning is, but I don't the repeat behaviour is.

**Comment by stonier** [comment]
With the new scheduler, not getting this warning any longer. Reopen if you see it again.
