### ISSUE TITLE
Non auto-invite removes application namespace

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#103]
Recently, my android-robot-apps-pairs stopped working, what was due to mismatching topics as described in issue #101.

However, the Android-robot-apps pairs are working for the TurtleBot and hence I started looking for the difference. One difference I found, is that I had the auto-invite for the public master turned off.

Turning this option on, somehow gets the application namespace added and the android-robot-apps-pairs start working again.

I don't believe this is supposed to work like that...

**Comment by stonier** [comment]
The application namespace for standalone mode got changed to match what was done in pairing. I suspect you were testing a long time ago in that standalone mode. This commit brought in a namespace underneath '/application' even in standalone.

e89bb6d05a041513f1aa39979696dacf6f6478b7

**Comment by stonier** [comment]
Hmm, more to this than that.

**Comment by stonier** [comment]
Note, auto_invite is the paired_master.py script's parameter. Nothing to do with concert and conductor.

**Comment by stonier** [comment]
Note, Marcus was using the robot remocon to invite the private master.

**Comment by stonier** [comment]
Got it.

1) The paired master on auto-invite was relaying a SimpleInvite request with application namespace of '' (empty string)
2) Android was using the original Invite service and passing an application namespace that was the resolved  gateway namespace (hence no application tagged on the end).

This logic inconsistency came about when we introduced the auto-invite relay to hydro to make things simpler. Unfortunately it didn't get into the hydro android code.

This should become irrelevant with @corot's new updates for igloo. But likely we have other bugs :P
