### ISSUE TITLE
Put the platform compatibility check under runnable apps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#111]
Currently it is done before creating the pre-installed list and only capabilities checking is done for runnable apps.

Works...but not terribly logical to future maintainers of the code.

**Comment by stonier** [comment]
Some discussion at https://github.com/robotics-in-concert/rocon_app_platform/pull/110/files#r8092975

**Comment by bit-pirate** [comment]
Also related to #112 .

**Comment by stonier** [comment]
Done in a45d5a937d724108b29cd70099f676fe83744a06
