### ISSUE TITLE
Make usage of roslaunch's <required> tag standard for rapps

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#127]
All (r)apps we have developed so far require all nodes to be running and re-spawning dead nodes usually is not working.

Hence, I suggest we introduce the `<required>` tag in our rapp launchers to clearly shutdown apps, which misbehave. This would make it much easier for the app manager to track the status of apps.

Thoughts?

PS: The above has already been implemented in the capability server and showed good results in usability so far.

**Comment by stonier** [comment]
Good idea, will update the rapps in our current concert repos.
