### ISSUE TITLE
Threadify start/stop apps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#128]
These functions right now make service callbacks very expensive to the point where a conductor can't terminate before roslaunch catches up with it.

Put the work in threads and maintain some state for the app manager - starting, running, stopping, idle.

**Comment by stonier** [comment]
Problem identified in https://github.com/robotics-in-concert/rocon_concert/issues/164

**Comment by stonier** [comment]
Hrm, do we want to do this...it's a massive change.
- Android, rqt, conductor, pairing all use this structure
- A non-blocking pub-sub service would be nice, but....
  - The conductor calls them in ros shutdown hooks - services, not pubsubs only work in this call.

**Comment by bit-pirate** [comment]
> Hrm, do we want to do this...it's a massive change.

Yes. I think, this would be a good addition as well.

> The conductor calls them in ros shutdown hooks - services, not pubsubs only work in this call.

Is it possible to move the shutdown sequence out of the shutdown hooks and add a _shutdown_ state to the conductor, in which it spins and sends out shutdown messages until all are received?

**Comment by stonier** [comment]
Actually, the second shutdown problem is not a problem. The conductor is calling the invite service, which can stay the same - no problems there.

That means I can really try out the idea of a non-blocking pub-sub style service. People who want the response, can write a callback, or block themselves if they want to. If they don't want to wait for the response, they just send the publish command.

**Comment by stonier** [comment]
> Is it possible to move the shutdown sequence out of the shutdown hooks and add a _shutdown_ state to the conductor, in which it spins and sends out shutdown messages until all are received?

That's generally what the conductor already does, but its hampered by the fact that the app manager's service callbacks which are trying to do alot of stop app work in their callbacks (thus blocking response to the conductor).

A short term hack would be to create a subscriber in the app manger that listens for uninvite requests and handles uninvites without blocking the other end (and without responding either). The long term solution should be to do these things in threads and provide the appropriate responses without forcing the other end to block.

**Comment by stonier** [comment]
> Is it possible to move the shutdown sequence out of the shutdown hooks and add a _shutdown_ state to the conductor, in which it spins and sends out shutdown messages until all are received?

A more direct answer - no we can't move the shutdown sequence. What we have is there explicitly to handle what happens when the concert receives a shutdown signal. At this point there is no regular ros environment anymore. All that is left is the last breath - the shutdown hook space.

The only possible alternative might be to include a non-ros connection (xmlrpc?) that doesn't require a ros master to be around.

**Comment by stonier** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/commit/2c645128c4ef78e5025e8472c72cb740f992d858 nullifies an immediate need for threading everywhere, or the use of non-blocking service pairs. It doesn't do anything with start apps, and there isn't an urgent reason for speeding up the starting of a group by the scheduler, so avoid this complication for now.
