### ISSUE TITLE
Add a screen output option to the app manager standalone launcher

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#132]

**Comment by stonier** [comment]
Actually doesn't have a private parameter yet...just `/rocon/screen`.

```
 TODO : additionally a private parameter for the app manager so
    # people can configure this from yaml or roslaunch instead of rocon_launch
```

Should it have a private parameter, or should we just re-use `/rocon/screen`?

**Comment by stonier** [comment]
Made a private parameter and launcher args in `standalone.launch`. You don't want a single app manager setting a global rocon parameter.
