### ISSUE TITLE
rapp launch file cannot be launched in root namespace

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_app_platform#133]
I received this error while launching a rapp:

```
App Manager : Launching 'bwi_orchestration_rapps/door_handler' underneath /
<include> tag has an empty 'ns' attribute
```

I wasn't planning on launching the app in the root namespace, but this probably needs to be fixed nonetheless.

**Comment by stonier** [comment]
This is coming from https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp.py#L285

For some reason, your application namespace is getting set to be the empty string. How are you running the app manager in this situation?

This variable has two places that it could get set that I can see:

1) When initialised and there is no gateways found and the `~robot_name` parameter is the empty string.
- https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L142
- https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L147

2) When invited by a concert - it will be the empty string if there are no gateways found (https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L318)

I think 2) perhaps should default to the behaviour of 1). That would automatically fix the situation.

**Comment by piyushk** [comment]
The app manager wasn't able to retrieve the gateway name because of this bug: https://github.com/robotics-in-concert/rocon_multimaster/issues/242. I forgot to forward /clock to that gateway, and the app manager never came out of this line. https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L640

Your solution will fix this problem. However, should we not allow launching applications in the root namespace?

**Comment by stonier** [comment]
With that last commit it now defaults to the same behaviour as when initialising without a gateway name, i.e. parameter ~robot_name.
