### ISSUE TITLE
Meta-Rapps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#137]
Rapps right now don't let you have multiple implementations of chirp. 

For example, rocon_apps/chirp and turtlebot_apps/chirp are NOT the same thing in the small minded intelligence of the app manager. 

From the resource scheduler's vastly superior intelligence though, chirp should be the same thing and requested/allocated as such.

Handle this by having a meta-rapp which defines the unique name, default description and public interface. Remaining files would constitute an implementation of that rapp. We have precedence with the capabilities and capability providers.

**Comment by bit-pirate** [comment]
I suggest to sync with the naming scheme we introduced for capabilities, that is a _capability_ consists of an _interface_ and one or more _providers_.

**Comment by stonier** [comment]
Been doing some more thinking about this. Rapps will have bunny behaviour - they're likely to proliferate. It would also be a pain in the ass for someone just playing around with a simple rapp idea to have to develop both (remember rapp developers can be alot less knowledgeable about robot software than capability developers, they're also more likely to learn with rapps than capabilities).

## Germ of Idea

Just have one definition of a rapp. Inside that definition, we introduce some new points:
- _Virtual Rapps_ : a rapp is virtual if it specifies no launcher.
- _Parent Specification_ : a rapp variable (type resource string) that is reference to a rapp that defines public_interface, public_params and a full rapp description (name, display name, description). This reference can be a self-reference (maybe assumed as self-referring if this variable is not present.
- _Variable Overloads_ : if using a parent spec, display name, description and icon are optionally overloadable.

_Questions_: what if the parent itself has a parent - should we support nested references? Do we allow virtual rapps to have parents? Do we care if virtual/parent apps specify compatibility uri's?

## Examples

**Virtual Rapp** - note no launcher, nor compatibility rocon uri:

```
# rocon_apps/chirp
display: Chirp
description: Make an audible "chirp" sound.
icon: rocon_apps/chirp_bubble_icon.png
public_interface: rocon_apps/chirp.interface
public_parameters: rocon_apps/chirp.parameters
```

**Implementation Rapp** - a turtlebot chirp implementation with parent specification and overloaded description.

```
# turtlebot_apps/chirp
description: Make a "moo" sound.
launch: turtlebot_apps/chirp.launch
compatibility: rocon:/turtlebot
parent_specification: rocon_apps/chirp
```

**One-Shot Rapp** - not virtual, but no parent specification either, satisfies current and simple user's (or rapid prototyping) use case.

```
# gopher_apps/chirp
display: Chirp
description: Make an audible "chirp" sound.
icon: gopher_apps/chirp_bubble_icon.png
launch: gopher_apps/chirp.launch
compatibility: rocon:/gopher
public_interface: gopher_apps/chirp.interface
public_parameters: gopher_apps/chirp.parameters
```

## Benefits

This design lets us have split virtual and implementation apps and standalone implementations at the same time. It also lets us keep a legacy style throughout the concert.

Another benefit is that the rapp index - it needs just one (i.e. not separate meta index + implementation index). We dump all styles of rapps there. We can easily create an api or a ui that indexes all these rapps and graphically visualises each rapps' relationship with others around it.

## Concert Perspective

Just to be clear - the concert resource scheduler will always see rapps by their parent. e.g. above, the resource scheduler will be interested in rocon_apps/chirp rapps - it won't care if it's a turtlebot_apps/chirp or pr2_apps/chirp implementation.

**Comment by stonier** [comment]
@jihoonl, @bit-pirate, @piyushk, @jack-oquin any thoughts?

**Comment by jack-oquin** [comment]
If requests always specify virtual rapp names, do clients always declare the virtual names, or is there an implied look-up step to resolve them when a client enters the concert?

**Comment by stonier** [comment]
The conductor will get all the info - implementation rapp name as well as top-most parent rapp name (to be technically correct with the above, that won't always be virtual). I was thinking the conductor should just advertise the top-most parent name. There is no reason for the concert (as yet) to have the exact implementation name.

**Comment by bit-pirate** [comment]
> It would also be a pain in the ass for someone just playing around with a simple rapp idea to have to develop both

Developing a capability (in terms of specification) has little to no overhead compared to the above suggestion. I'm in favour of using the naming used for capabilities to make it simpler to understand - also shows the close connection of both.

Independent from the above, I'd say there is no strong need to actually differentiate _Virtual Rapp_, _Implementation Rapp_, _One-Shot Rapp_. As far as I understood this boils down to optional arguments. I would also suggest to simplify _public_interface_ and _public_parameters_ and use _interface_ and _parameters_ instead. Also, for capabilities parameters are part of the interface.

**Comment by jack-oquin** [comment]
+1 Capabilities seem attractive to me. 

Does [this wiki page](http://wiki.ros.org/capabilities) reflect the current design?

A rapp seems to embody the notion of a mobile robot of a certain type that can run a specific launch file. If that can be expressed using capabilities, it could simplify the user interface while making it more powerful. That is not often possible when making design trade-offs.

**Comment by stonier** [comment]
I agree, it's not much overhead to make interface and implementation for every rapp, but that work does start to multiply - two separate repositories, indices, etc. So is it necessary? Also the rapp developer will often not be as seriously dedicated as the capability developer. Capabilities are also a bit more complex - they have semantics and capability dependencies to handle that rapps don't need to consider. Certainly if we did strictly separate interface and implementation, yes, I'd like to use the same terminology we had for capabilities.

So back to the point, I'd like to avoid this complexity and still keep the idea of a single rapp definition. Like C++ classes - there is just one definition, the class. The construction of this rapp can reflect the simple and complicated uses at the same time without becoming too cumbersome. Note that I'm not differentiating the rapps explicitly - those examples just reflect different use cases.

I like keeping the `public_` expressions. Makes it very clear when the rapp mixes public properties exposed to concerts vs private implementation properties (such as capability dependency list, launchers, possibly later we may have other private variables) only used by the app manager to start the app.

Capability parameters shouldn't be part of the public interface. Certainly a rapp is in control of setting those parameters to suit the task it is assigned, but it should not have to publicly expose those parameters to the outside world. Sometimes it may wish to expose _some_ of them, but this can be easily done by reflecting a public parameter to a capability parameter internally.

**Comment by stonier** [comment]
> Does [this wiki page](http://wiki.ros.org/capabilities) reflect the current design?

Should be close. It's not yet quite the finished product but not far off.

> A rapp seems to embody the notion of a mobile robot of a certain type that can run a specific launch file. If that can be expressed using capabilities, it could simplify the user interface while making it more powerful. That is not often possible when making design trade-offs. 

Are you talking about the public interface it dumps in the concert? i.e. instead of individual pubs/subs/services/actions, grouped collections like the capabilities represent?

Right now the capabilities are just intended as a way of writing rapps in a much simpler way. They're not exposed to the concert at all. The same delivery rapp that uses different navigation stacks on different robots can be written and installed for both robots (by expressing dependencies on capabilities rather than navigation-stack-a and navigation-stack-b). Exposing capabilities to the concert brings in many complications that I feel would be seriously hard to control. e.g. selecting and choosing to run capabilities x-y-z in parallel. A robot app developer can potentially know issues that can arise from mixing capabilities and even optimising (paremeterising) capabilities on a particular robot for a task. Shifting this job to a concert service developer starts requiring them to know detailed robot specific knowledge (bad). In addition, resource scheduling gets complex - supposing you ask for image and diff drive capabilities to do teleop, you then have to make sure those requests also get tied to a single device. Alot of groups have tried to do similar to this, but actually I've not seen one of them progress very far.

What is of interest to me at the higher level is not control of the granularity at the capability level, but control of tasks. The higher level doesn't need to know about the robot in detail then and there is a 1-1 correspondence between task and device. That seems to be more workable and it generally reflects the way humans work as well. Ideally you assign people tasks and let them work out how to best accomplish that task. When you try and manage every individual part of their task, then the system doesn't work so well.

Having said that, I am a bit curious about the best way to represent a task's (i.e. rapp) public interface. Bundling these in ways that make sense to concert service developers, or even providing api wrapping those bundles makes sense. Even writing a higher level api for interacting with a rapp's public interface would be nice. But it's not something I have time to plan for right now.

**Comment by jack-oquin** [comment]
I don't really understand the capability design. 

I am imagining a language for expressing the things individual devices can do, like the fact that a robot with a camera can "take a picture", while one without cannot. One with an arm can "pick up an item", etc. That seems more complex than a rapp, but presumably includes its semantics as a subset.

The question is whether the additional semantic power is worth the complexity, and whether most or all user requirements can be satisfied via that mechanism. Fewer mechanisms are generally better, but I lack the insight to suggest a clear answer.

**Comment by stonier** [comment]
> Fewer mechanisms are generally better, but I lack the insight to suggest a clear answer.

I am generally feeling that way too. Would love to have a serious design discussion with a few different parties about how resources should be presented at concert level. However the rapps have too much momentum right now, and they work, even if sometimes that means writing a new rapp - at least there is not much code duplication since a rapp mostly recycles the same nodes. 

On the plus side, it's trying something different and will be a learning experience.

**Comment by bit-pirate** [comment]
> I don't really understand the capability design.
> 
> I am imagining a language for expressing the things individual devices can do, like the fact that a robot with a camera can "take a picture", while one without cannot. One with an arm can "pick up an item", etc. That seems more complex than a rapp, but presumably includes its semantics as a subset.

Capabilities are the very basic thing a robot (or device) can do, such as _camera_ -> provide an image stream. There is not clear separation between applications and capablitites, e.g. currently navigation is an app, but it can also be seen as a capability. Our expectation is, that (in the ROS world) we start with a small set of simple and commonly used capabilities, such as _mobile base_ (also driving the robot around) and then work our way up, turning more complex features, such as _navigation_ and _move_arm_ into a capability.

Your examples seem more like tasks to me, which are currently represented by apps, e.g. turtlebot_panorama.

**Comment by jack-oquin** [comment]
There is considerable conceptual overlap. You all have more experience than I do about where to draw the line.

My current view of rapp scheduling is simple: each client declares a set of rapps that it can run; and each request specifies a specific rapp. While the client is assigned to the request, it is dedicated to running that rapp. When the request is closed, the client is available again for running any rapp it supports.

That is easy to explain and understand. Capabilities seem harder to grasp.

**Comment by jihoonl** [comment]
pairing_client should be in meta rapp? or implementation rapp?

https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_apps/apps/talker/talker.rapp#L7

**Comment by stonier** [comment]
pairing client should be a meta-variable since it communicates across only the rapp's public interface.  Ideally this should become a list of compatible applications for pairing.

I have a thought though that pairing functionality should someday move to rocon interactions because that is where we will do human authentication, but that day is quite a ways off.

**Comment by stonier** [comment]
This discussion rounded off and moved into other issues and an implementation.
