### ISSUE TITLE
Rapp manager use new rapp module

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#140]
Use #139 to advertise abstracted rapps to the concert.

**Comment by stonier** [comment]
Don't think we even need to change Rapp.msg here, just replace the resource name with the topmost parent name. 

The only reason for adding the extra information would be for introspection at this stage.

**Comment by jihoonl** [comment]
Do you mean Rapp.msg this(https://github.com/robotics-in-concert/rocon_msgs/blob/hydro-devel/rocon_app_manager_msgs/msg/App.msg)?

**Comment by stonier** [comment]
Yes.

**Comment by jihoonl** [comment]
The following points are discussed
- Merge rocon_app_manager.Rapp and rocon_app_utilities.Rapp
  - Inherit, Composition, wrapper.. not decided
- Store both `ancestor_name` and `implementation_name`
- Use `ancestor_name` for publicize rapps.

**Comment by stonier** [comment]
Sounds good.

**Comment by stonier** [comment]
@jihoonl is this finalised?

**Comment by jihoonl** [comment]
Rapp has `ancestor_name`, `parent_name`, and `implmentation_name` all three. 
We have concluded `rapp_manager` to use `ancestor_name` to publicize its available rapps.
Closing this.
