### ISSUE TITLE
Rapp Index Viewer

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#141]
Tossing this idea around right now - might be useful to have a viewer for the rapp tree. Ascii tree, dotgraph generator, or rqt dot plugin?

**Comment by jihoonl** [comment]
`rocon_app` script would be sufficient for now?

**Comment by stonier** [comment]
That's ascii output right?

**Comment by stonier** [comment]
A dotgraph viewer would still be best, especially for helping other people understand. These are not difficult to copy/modify from other rqt plugins. So I'd like to keep this open till we have an rqt plugin for it.

**Comment by stonier** [comment]
The command line tool is good enough now - I updated the syntax and highlighting so it's much easier to read.
