### ISSUE TITLE
develop rapp indexer testing set

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#145]
To obtain the format of index-ed rapp and to test out whether indexer generates correct output.

The test set should include corner cases.

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/blob/rapp_module/rocon_app_utilities/doc/test_cases.rst

Test cases updated.

**Comment by stonier** [comment]
:+1:

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/commit/9b4564a42255e929aa2d516e7cb66355ac89a399

**Comment by jihoonl** [comment]
Rapp indexer as well as rapp test cases are implemented here.

https://github.com/robotics-in-concert/rocon_app_platform/tree/rapp_module/rocon_app_utilities/tests
