### ISSUE TITLE
Rapp indexer API

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#153]
@stonier  

Initially designed APIs of Rapp indexer. Any comment? 

http://192.168.10.129/rocondoc_dev/rocon_app_utilities/html/indexer.html

**Comment by stonier** [comment]
Don't have a public use case for the `get_rapp` right now (but its getting used in testing and may be useful for something in the future). Let's just change the public api terminology so the obvious is the one that is for public consumption, e.g.
- `get_complete_rapp` -> `get_rapp`
- `get_rapp` -> `get_raw_rapp`
- `get_compatible_rapps` -> drop the `implementation_only` flag (can't think of a use case)
- `get_compatible_rapps` -> raise an exception when two implementation of an ancestor are found
- `get_compatible_rapps` -> make sure they return fully resolved rapps
- `get_nearest_parent` -> let's drop it, can't think of a need for it.
- `get_ancestor` -> let's drop it too, can always revive from git history
- `to_dot` -> make a stub, implementation later (see our rqt plugins for examples)

**Other Comments**

Some other points that came up in discussion.
- Rapps themselves should store their name and their ancestor name. The app manager uses these ancestor names, so each rapp should have something like an accessible `name` and a `ancestor_name` variable. `parent_name` should also be included for completeness.
