### ISSUE TITLE
Parameter for disabling capabilities support

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#163]
Allow disabling capabilities support by setting a parameter in the launch file in order to speed up the startup time of the app manager for users not requiring capabilities.

Requested by @stonier.

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/commit/dda2d980b27d0461b4923cc81a7e3073a9e8375a provides disable argument.
