### ISSUE TITLE
Rapp upgrade hangover jobs

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#169]
List of work to do post the major rapp upgrade.
- [x] rocon_app_utilities global script needs a prefix (see below)
- [x] rocon_app_utilities has tests, but no cmake test rules
- [x] rocon_app_utilities to use roslint and get it passing
- [x] rocon_app_utilities code analyasis (e.g. remove unused imports), pep8
- [x] drop pairing client information from rapps (let's discuss this first)
- [x] correct reference to rocon_utilities.Rapp in rocon_app_utilities/indexer.py 
  - Should be rocon_app_utilities.Rapp?
- [x] rocon_app_manager code analysis/pep8.
- [x] check the incompatible app list publisher is working as it should
  - I noticed a comment `# TODO: Currently blacklisted apps and non-whitelisted apps are not provided yet`
  - Also the latched information may be lost if the remote controller changes
  - i.e. in  `init_services`, it recreates the publisher, but doesn't republish

**Comment by jihoonl** [comment]
how do i use roslint?

**Comment by jihoonl** [comment]
> rocon_app_utilities has scripts, but no cmake install rules.

The script is installed in setup.py. Does it need to be installed in both local and global bin?

**Comment by stonier** [comment]
> how do i use roslint?

See the root `CMakeLists.txt` in `rocon_gateway` (by piyush), `rocon_scheduler_requests` (by Jack) and `rocon_interactions` (by myself) for examples. The [wiki](http://wiki.ros.org/roslint) lists the make targets you can use.

**Comment by stonier** [comment]
> The script is installed in setup.py

Ah, a global installation. We need to be careful with global script installs. There is a convention of sorts to use a prefix for global scripts (e.g. the ros in rostopic, rosservice, rosbag). I tend to use `rocon_` or `concert_`.  Perhaps `rocon_rapp` or `rocon_rapps`?

I updated the list above.

**Comment by stonier** [comment]
Don't worry about doing these yet - these are non-functional issues. I'll check its working, then merge and then this list can be attacked (small steps).

**Comment by jihoonl** [comment]
how about `rocon_app` since use `rapp` as abbreviation of `rocon_app` so far.

**Comment by stonier** [comment]
> how about `rocon_app` since use `rapp` as abbreviation of `rocon_app` so far. 

:+1:

**Comment by jihoonl** [comment]
gateway connection types are not directly utilizable as `.interface` introspection. Should we drop one or keep both.

Gateway connections types are 
`["publisher", "subscriber", "service", "action_client", "action_server"]`

But interface specs are

`
 subscribers: []
 publishers: []
 services: []  
 action_clients: []
 action_servers:  []
`

**Comment by stonier** [comment]
Yeah, the 's make sense here, in the gateway those are used for the specification of a single gateway  rule so let's not reuse them. Still a frozen set module would be nice since these keys are used in multiple places in the file.

**Comment by jihoonl** [comment]
connection key discussion is now in new issue https://github.com/robotics-in-concert/rocon_app_platform/issues/178

**Comment by jihoonl** [comment]
remain jobs are created as new issue. Others are implemented.
