### ISSUE TITLE
Public parameters for rapps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#170]
Right now we send parameters to start rapps with and it all works, but....
- _Validation_ : you could set any parameter and hack the system, e.g. rosversion!
  - Check each parameter coming in with start_rapp commands, ignore it if it isn't public, set it otherwise.
- _Introspection_ : provide idl information so that services know what parameters they can set for a rapp.

**Comment by stonier** [comment]
Interesting question - should parameters have type information as well?

**Comment by stonier** [comment]
Rapps need a public parameters file

**Comment by stonier** [comment]
Talking with @jihoonl, we both think that using launch args is the best way to expose public rapp parameters. The launcher can then play around with these args (e.g. if, unless in roslaunch xml) or pass these args to internal parameters as it wishes.

**Comment by piyushk** [comment]
I can describe my use case as necessary, however it is not too urgent. Mostly it is setting arguments in a launch file to decide what parameters get set, and what nodes get launched. It would be nice to be able to specify this when launching the app.

**Comment by stonier** [comment]
Args for public parameters sounds good. I'll tackle this after the demo.

**Comment by jihoonl** [comment]
Todos to enable public parameter
- rocon_app_manager
- concert_simple_scheduler
- concert_resource_pool
- rocon_qt_app_manager
- concert_schedulers
- rocon_interactions

**Comment by jihoonl** [comment]
~~Speed configurable concert_teleop would be good test for public_parameter~~

Configurable Talker would be better. Fork talker from rospy_tutorials and modify to use param for publish frequency and message.

**Comment by jihoonl** [comment]
#243 closes this issue.
