### ISSUE TITLE
Logging out rapp loading failures

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#171]
We have two tools that should provide warning or error information when things go wrong with your rapp:
- `rocon_app` - great for when you're writing your new app and want to check your rapp is valid.
- `rocon_app_manager` : which should show all the first problems but also further checks at runtime

**Basic Checks** : for rocon_app and rocon_app_manager
- Invalid specification when reading the `.rapp` file
- Not in whitelist or in blacklist - maybe not essential as it will get spammy
  - we have app manager publisher for that
- Problems when loading (resolving) everything into the `rocon_app_utilities.Rapp` class
  - Make sure to check things like the launcher exists and can be found

**Runtime Checks** : for rocon_app_manager only
- When a rapp cannot find its required capabilities on the server
- When a rapp is not compatible with the rocon app manager.

**Comment by jihoonl** [comment]
all warning and errors are implemented.

**Comment by stonier** [comment]
@jihoonl It would be good to link to the commit that made the changes.
