### ISSUE TITLE
Wiki documentation for rapp upgrade

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#174]
Need to update the guide and make sure everything we need is in the sphinx docs.

**Comment by bit-pirate** [comment]
Guide has been updated. The sphinx documentation holding the spec is currently under review: https://github.com/robotics-in-concert/rocon_app_platform/issues/185

@stonier if you are happy with the information added to the guide, please close this issue.

**Comment by stonier** [comment]
I think we could use one tutorial about introspecting rapps on the package path (i.e. using the command line tool). That's definitely something a dev will/should be doing fairly regularly while building/debugging rapps. Not sure if the rapp tool is complete enough to really support this idea well yet though.

**Comment by bit-pirate** [comment]
> I think we could use one tutorial about introspecting rapps on the package path

+1 

I would add such a tutorial to the ROS wiki page for [rocon_app_utilities](http://wiki.ros.org/rocon_app_utilities). @jihoonl what do you think?

**Comment by stonier** [comment]
Yeah, I agree on rocon_app_utilities. Prefix it to the beginning create a rapp tutorial chain though?

**Comment by stonier** [comment]
@jihoonl _bump_

**Comment by jihoonl** [comment]
I am aware of it. I plan to tackle this in next sprint.

**Comment by jihoonl** [comment]
I have created a tutorial to describe invalid rapp cases and explanation on command line tools.
 Let me know if more information is needed.

[rocon_app_utilities wiki](http://wiki.ros.org/rocon_app_utilities)
[Introspect Rapps](http://wiki.ros.org/rocon_app_utilities/Tutorials/indigo/Introspect%20Rapps)

**Comment by stonier** [comment]
**Wiki Page**

On the [wiki page](http://wiki.ros.org/rocon_app_utilities) you need to make sure links don't break when jurassic comes out. Important one here is the rapp spec. link which points to an indigo version of the code api docs. Either version it, or just tell them to read the code api docs.

Or move all content to tutorials which are version scoped, leaving the main page easy to version scope with links to code api and tutorial chains - see below. I tend to do this alot now.

This latter option is probably the best option. That main page will get crowded with indexer information piling in on top of the rapp command line information later.

**Comment by stonier** [comment]
The tutorial too is not so much about introspecting rapps, but troubleshooting rapps.

Perhaps the following - two tutorials:
- Introspect Rapps : moved from the main page, about how to use the rapp tool
- Troubleshooting Rapps : basically the content now from the Introspect rapps

And on the main page, just a link to the rapp specification docs and a tutorialchain starting from 1. (wrapped in a version scope for indigo).

**Comment by jihoonl** [comment]
Wiki has been updated as suggested. I have moved command line usage as Introspect Rapps tutorial and rename the original one as trouble shooting.

[rocon_app_utilities wiki](http://wiki.ros.org/rocon_app_utilities)
[Tutorial](http://wiki.ros.org/rocon_app_utilities/Tutorials)

**Comment by stonier** [comment]
I just tweaked them a little (moved create a rapp into their midst) and added them to the [guide](http://wiki.ros.org/rocon/indigo/Guide).

Looks good to me now. @bit-pirate, reopen if you think of anything.

**Comment by bit-pirate** [comment]
Hm, someone moved the rapp-specific tutorials from rocon_app_manager to rocon_app_utilities thereby breaking the tutorials chain for rocon_app_manager. I fixed it. Please be careful with this in the future. Except this, tutorials are looking good.

**Comment by stonier** [comment]
That would be me - I carefully tracked down a couple of those tutorial chains, but must have missed one, my bad.
