### ISSUE TITLE
provide white/black listed rapps in incompatible rapp topic

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#176]
> TODO: Currently blacklisted apps and non-whitelisted apps are not provided yet

https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L84-L85

**Comment by stonier** [comment]
This doesn't point to the right line of code, nor makes much sense right now. Reopen if necessary.
