### ISSUE TITLE
Syncing Connection key between gateway and app manager

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#178]
- [ ] in `rocon_app_manager/rapp.py` use a module frozen set for the connection keys
  - See `rocon_gateway/utils.py` for an example.
  - Maybe even use that one and the `create_empty_connection_type_dictionary()` directly?

**Comment by jihoonl** [comment]
gateway connection types are not directly utilizable as `.interface` introspection. Should we drop one or keep both.

Gateway connections types are 
`["publisher", "subscriber", "service", "action_client", "action_server"]`

But interface specs are

`
 subscribers: []
 publishers: []
 services: []  
 action_clients: []
 action_servers:  []
`

**Comment by jihoonl** [comment]
**From Dan**

Yeah, the 's make sense here, in the gateway those are used for the specification of a single gateway  rule so let's not reuse them. Still a frozen set module would be nice since these keys are used in multiple places in the file.

**Comment by stonier** [comment]
Dropping this for now as it's not terribly important.
