### ISSUE TITLE
zsh/tcsh env-hooks for rocon_app

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#184]

**Comment by stonier** [comment]
@jihoonl use 'closes #xxx' hooks in your commits so these issues close.

**Comment by stonier** [comment]
Ach, my bad - this is a todo job, not related to that pull request.

**Comment by bit-pirate** [comment]
You can also do this afterwards by adding _closes #XXX_ in the PR description (not title).

**Comment by stonier** [comment]
These are in. Whether they work or not is another question! Open new bug reports if later we find out they dont.
