### ISSUE TITLE
Rapp specification review

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#185]
My comments after reviewing the rapp specification documentation (`/rocon_app_platform/rocon_app_utilities/doc/html/rapp_specification.html`):
1. Change the order of the paragraphs in "Rapp Types"
   -  put the table last and add a caption for it: "Rapp Parameters"
2. Meaning of "nearest parent" not clear
3. Meaning of "rapp chain" not clear
   - An example of a rapp chain would be good. This could easily explain the "rapp chain" and at the same time the "nearest parent".
4. Parameter name and type name mismatch:
   - If `parent_name` is not present, it is an ancestor. So, why is this parameter not called `ancestor_name`? Or visa-versa, the type should be called "Parent Rapp", if the paramater remains as `parent_name`. 
5. "parent_name and public_interface are mutually exclusive."
   - There should be at least a warning, if some specifies both. Has this been implemented yet?

**Comment by bit-pirate** [comment]
@jihoonl @stonier please comment my comments. Thx.

**Comment by bit-pirate** [comment]
PS: I linked the specs on the ROS wiki: http://wiki.ros.org/rocon/indigo/Guide#rocon.2BAC8-indigo.2BAC8-Guide.2BAC8-The_Appable_Robot.Rapp_Specification

**Comment by stonier** [comment]
With regards to 4. - it should probably remain as is:

>  If `parent_name` is not present, it is an ancestor. So, why is this parameter not called `ancestor_name`? 

Because you can have a parent who is not an ancestor. e.g. given four rapps in a chain:

```
child -> parent-child -> parent-child -> parent
```

Only the last one is an ancestor.

Given Marcus' confusion, 2. and 3. probably need some clearer guidance - picture?.

**Comment by stonier** [comment]
I think also it could do with a leading `Overview` paragraph. It takes quite a bit of mental juggling for a newcomer to work out what this spec is talking about.

Question though - should we put the overview here or on the wiki? I usually tend to the wiki, but I think we need it here for the specifications to make sense.

**Comment by stonier** [comment]
Re 5. I'm not sure, @jihoonl?

**Comment by jihoonl** [comment]
The rapp with both parent_name and public interface will fail to pass rapp validation and be mared as invalid rapp with current imlementation.

**Comment by bit-pirate** [comment]
> Because you can have a parent who is not an ancestor. e.g. given four rapps in a chain:
> 
> child -> parent-child -> parent-child -> parent
> Only the last one is an ancestor.

So, an ancestor is a parent without a child? If that is true, then there needs to be a definition for ancestor, since this meaning can not directly be derived from the English word alone - at least not for non-native English speakers ...

> I think also it could do with a leading Overview paragraph. It takes quite a bit of mental juggling for a newcomer to work out what this spec is talking about.

Definitely.

> Question though - should we put the overview here or on the wiki? I usually tend to the wiki, but I think we need it here for the specifications to make sense.

The spec should contain this overview. Just keep it concise and focused on what is need to understand the spec. Without it the specification as it is, is hard to understand.

> probably need some clearer guidance - picture?.

A few lines of text or a picture - both fine to me.

**Comment by bit-pirate** [comment]
Btw, why is a virtual rapp not allowed to have a parent?

**Comment by stonier** [comment]
I think my picture needs an upgrade ;)

@bit-pirate : think about it like c++ classes. 
- **Child Rapp** ~ class that inherits from another
- **Ancestor Rapp** ~ class that does not inherit from anyone, may or may not have children.
- **Virtual Rapp** ~ class that has pure virtual methods (i.e. is not runnable)

The only difference between what we have and classes is in the virtual case - we constrain the virtual class so that it has to be an ancestor (i.e. not allowed to inherit from anyone and thus top of the pile)

**Comment by stonier** [comment]
One major feature that is missing in this spec is an explanation of each variable and the syntax it must use. It just shows their relationships and a couple of examples.

**Comment by bit-pirate** [comment]
Alright, after talking with @stonier I now know the reasons
-  why virtual rapps have to be ancestors -> simplification
- and why children cannot define a public interface, i.e. inheritance, but no extensions -> simplification, motivation for splitting rapps).

This information needs to be added to the spec.

Furthermore, I would also like to see it (more) highlighted, that an ancestor has no parent. I only understood the full implication after discussing it here.

**Comment by stonier** [comment]
:+1: good points/conclusions.

**Comment by stonier** [comment]
@jihoonl Last 3 points are recommendations for the rapp indexer sphinx documentations.

**Comment by jihoonl** [comment]
I have updated document. Check it out.

http://192.168.10.129/rocondoc/rocon_app_utilities/html/rapp_specification.html

> and why children cannot define a public interface, i.e. inheritance, but no extensions -> simplification, motivation for splitting rapps).

I was not sure how to re-phrase it in the document. Hopefully it is covered in updated description

**Comment by stonier** [comment]
```
Virtual Ancestor : is meta rapp contains public interface but any platform-dependent information
```

I think you mean `not any platform-dependent`. Perhaps should be `not any implementation-dependent` (platform usually conveys immediate thought of cross-platform things).

**Comment by stonier** [comment]
Also 
- `infomration` -> `information`
- find out from marcus what the capabilities spec is (and replace that TODO).

**Comment by stonier** [comment]
Other than that, documentation looks great. @bit-pirate how does it look now to an ignoramus? :stuck_out_tongue_winking_eye:

**Comment by jihoonl** [comment]
plan to fix the broken links and namings.

e.g) 
Rapp Parameter link. 
`Virutal Rapp vs Rapp Implementaion` -> `Virutal Rapp vs Implementation Rapp`
`Child Rapps Vs Ancestor Rapp` -> `Child Rapp vs Ancestor Rapp`

**Comment by stonier** [comment]
The only other thing that might be nicer is a diagram for the `child -> parent-child -> ...` chain to make that clearer (that was a very rough, kinda confusing line from me). A uml class diagram might make that immediately clear to software people. But wait to see if it makes sense to marcus.

**Comment by bit-pirate** [comment]
[nitpicker mode on] :

Details:
- Please use punctuation; e.g.:
  - hard to read: _is meta rapp contains public interface but any platform-dependent information. not-executable. e.g) rocon_apps/teleop_
  - easier to read: _is a meta rapp; contains a public interface and no platform-specific information; not executable; example: rocon_apps/teleop_
- not sure what you want to say here at Implementation Child: _contains platform dependent data but public APIs._. Do you mean: _contains platform-specific data but **no** public APIs_?
- Would move _Rapp Parameters_ after _Design Decisions_, which are more important for the understanding of rapps.
- Parent VS Ancestor
  - The whole children, parent and ancestor thing is still not easy digestible.
  - Suggestions:
    - Put _Parent VS Ancestor_ before _Child Rapps Vs Ancestor Rapp_ and turn it into _Children, Parents and Ancestors_ (since it explains all three)
    - Add behind _Parent is a rapp where child inherits from._: _A child can at the same time be a parent, if another child inherits from it._
    - Cannot understand _Ancestor is the root of parent if child is referencing another child as parent_. Maybe just: _A Parent not inheriting from another Child/Parent is an Ancestor_.
    - drop _In the example case below, the right most parent is an ancestor._ and instead change in the diagram the last `parent` to `parent (anchestor)`
    - I would say that simple diagram is enough (yes, even for me). Would only change _parent - child_ to _parent/child_, but that's just a style question.

Other than that, its looking good. Good job!

[nitpicker mode off]

**Comment by bit-pirate** [comment]
Regarding the missing capability info, specifying a type here is a bit more difficult, see this rapp for example: https://github.com/yujinrobot/kobuki/blob/hydro-devel/kobuki_apps/rapps/random_walker/random_walker.rapp

What do you recommend? 

My suggestion: Add `Type =`dict (details below)` in the table, add the following section to the rapp specification page as well as the kobuki_random_walker app to the examples.

---

_Capability Dependencies_
Specify for each capability dependency:

```
- name: <capability interface name>
    interface:
      topics:
        requires:
          <interface topic>: <rapp topic>
        provides:
          <interface topic>: <rapp topic>
      services:
        requires:
          <interface service>: <rapp service>
        provides:
          <interface service>: <rapp service>
      actions:
        requires:
          <interface action>: <rapp action>
        provides:
          <interface action>: <rapp action>
```

This format follows the capability interface specification: http://docs.ros.org/hydro/api/capabilities/html/capabilities.specs.html#module-capabilities.specs.interface

**Comment by jihoonl** [comment]
I have updated the document. 

http://192.168.10.129/rocondoc/rocon_app_utilities/html/rapp_specification.html

I am still hesitating to move the `rapp parameters` under `design descision`. 
`What` and `How` should come first then `Why` in my opinion.  
How do you think about it? @stonier

**Comment by stonier** [comment]
LGTM. I think it's readable enough in the present form. @bit-pirate re-open this ticket if you'd like further changes.

With regards to `what`, `how` and `why`, I think the `how` should always be a last resort. Most of the time we're documenting for a programming api which is essentially a `black box`.

The **what** is important  for obvious reasons - it describes what you need to put in and what you get out. 

The **why** for complicated black boxes is also really really important. That can help you understand the nature of the black box and will often mean the difference between someone using a black box correctly vs someone using it (unwittingly) incorrectly.

If you're getting to the **how** of things, then your documentation has probably failed. It typically means the user is having to look inside the code to work out how it's done. The `rapp_parameters` table to me is fine, it's part of the `what`.

**Comment by bit-pirate** [comment]
Looks good to me as well. One last request:

Please add kobuki_apps/random_walker.rapp (https://github.com/yujinrobot/kobuki/blob/hydro-devel/kobuki_apps/rapps/random_walker/random_walker.rapp) to the examples, because the other ones don't show the usage of capabilities.

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/commit/7fa9bad9f01ba3bfa8eb8da0d1ae0f19f7ceeb3f
