### ISSUE TITLE
Prefferred policy for rapps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#187]
Marcus' comments the other day and the turtlebot teleop examples really started highlighting a problem we will come across.

In testing and development and in general we're probably very very likely to find more than one compatible rapp on the package path. While rapp package whitelists can deal with this to some extent, quite often you'd like two implementations of a rapp inside a package (e.g. `my_funky_foo.rapp` & `my_funky_foo_experimental.rapp` or `crazy_teleop.rapp` & `old_grandma_teleop.rapp`). That's going to break with our current policy.

A mapping list of preferred/defaults going into the app manager/indexer functions might be useful.

For background, this issue came up with the capabilities development and a similar issue was implemented.

**Comment by bit-pirate** [comment]
For capabilities this is solved by setting a parameter for each capability at startup (via the roslauncher): https://github.com/osrf/capabilities/blob/master/launch/demo.launch#L28-L29

Here `name` holds the name of the capability interface and `value` contains the name of the default provider.

**Comment by jihoonl** [comment]
Any link where discussed about this issue in capability?

**Comment by jihoonl** [comment]
Seems like https://github.com/osrf/capabilities/pull/6 is relevant,

**Comment by jihoonl** [comment]
done by #248
