### ISSUE TITLE
rocon_app_utilities.RappIndexer is missing documentation

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#188]
http://docs.ros.org/indigo/api/rocon_app_utilities/html/indexer_api.htm is empty. Please fill it in.

**Comment by jihoonl** [comment]
Be relax. it is because of failure in jenkins. It nicely compiles and shows in my pc.

**Comment by stonier** [comment]
I'd like to leave this open till it's resolved - it's a problem for Marcus as we need documentation showing up for OSRF.

**Comment by jihoonl** [comment]
Putting myself out from assignee. I am not in charge of jenkins job.

**Comment by bit-pirate** [comment]
Has some a link to the doc job, so we can easily monitor it?

**Comment by stonier** [comment]
http://jenkins.ros.org/view/IbinS32/job/doc-indigo-rocon_app_platform/

**Comment by stonier** [comment]
It's throwing errors because rocon_multimaster is not built yet (which is in turn depending on common_tutorials). I don't know if that is the cause, but I'm not going to dig deeper just in case it happens to resolve itself once rocon_multimaster gets built.

**Comment by bit-pirate** [comment]
Build farm shows all green. Close this?

**Comment by jihoonl** [comment]
Confirmed that all docs are built well http://docs.ros.org/indigo/api/rocon_app_utilities/html/indexer_api.html
