### ISSUE TITLE
Confusing warning when unknown app is requested to be started

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#198]
Asking the app manager to start an unknown app results in a misleading warning, which complains about missing capabilitites. However, the true reason is that the rapp does not exist.

In the example below the rapp name has been mispelled - `kobuki_rapps/kobuki_random_walker` instead of 'kobuki_rapps/random walker'.

```
[INFO] [WallTime: 1397207297.417003] App Manager : request received to start app [kobuki_apps/kobuki_random_walker]
[WARN] [WallTime: 1397207297.417419] App Manager : The requested app 'kobuki_apps/kobuki_random_walker' is installed, but cannot be started, because its required capabilities are not available
```

The root cause lies in this section: https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L448-L464

So, the check is there, but parts of it have been commented out. I'm not sure why though. @jihoonl git blame shows you have commented this part out. If this is correct, please you let us know why.

**Comment by jihoonl** [comment]
It was because the entire logic of rapp retrieval has changed. preinstalled rapp is invalid anymore. 
and I forgot to add the validation check back :P
Will make the patch later.

**Comment by bit-pirate** [comment]
The above commit is actually the fix of the fix introduced by https://github.com/robotics-in-concert/rocon_app_platform/commit/65f4eaee8ecf056357f231258f503aeb4a0656db.
