### ISSUE TITLE
Generic robot teleop rapp for rocon_apps

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#199]
I'd like to start a discussion about a generic robot teleop (r)app, which can be used by a variety of robots.

Currently rocon_apps' teleop rapp (https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_apps/apps/teleop/teleop.rapp)  is only a virtual rapp. I'd like to turn it into a rapp implementation.

With the capabilities in place - the teleop rapp would depend on the std_capabilities/DifferentialMobileBase' capability (for now) (https://github.com/osrf/std_capabilities/blob/master/interfaces/DifferentialMobileBase.yaml) - it should be feasible to run it on different robots.

@stonier @jihoonl @dwlee @hughie thoughts?

**Comment by stonier** [comment]
Ancestor rapp based on capabilities sounds like a great idea - _the reference implementation_.

**Comment by bit-pirate** [comment]
There is a lot of code for this already:
- many robot-specific implementations:
  - Turtlebot has its own keyboard and joystick teleop (https://github.com/turtlebot/turtlebot_apps/tree/hydro/turtlebot_teleop).
  - PR2 has its own version: http://wiki.ros.org/pr2_teleop
  - many more robot-specific teleop implementations ...
- Yujin has its own closed-source implementation as well
- There is simple half-generic Python keyboard teleop node: http://wiki.ros.org/teleop_twist_keyboard
  - will its robot agnostic, it still is a specific implementation in terms of its functionality and in- and outputs
  - probably copied over from turtlebot or other existing teleop implementations
- There is a generic implementation here: 
  - The author focused on a fully generic implementation to fight the proliferation of teleop implementation
  - It has been released yet and looking at the history, I wonder, if it is still maintained. (https://github.com/skynetish/generic_teleop/issues/1)
- Last, but not least, there is also a Android teleop app

With all those options at hand, I'd like to discuss, which features this generic teleop app should have. The minimum requirements should be what's already available, i.e. keyboard and joystick control. Regarding keyboard control, I see there are differences in the key map. Some prefer the arrow keys, others the letter keys. Regarding joystick control, I see there are different controllers being used, which also can have different button/axis maps. On the other hand most nodes use the same output, that is `geometry_msgs/Twist`.

Furthermore it would great, if it would be easy to add more features. For example, for our Yujin robots we usually have a enable/disable function for the motor drive system.

With those features in mind, it looks like the `generic_teleop` package would be a good way to start, assuming it is maintained and will be released soon. Otherwise we might just move the turtlebot implementations out (maybe into ROCON or YOCS), make them generic and beef them up where necessary.

Thoughts? Comments?

**Comment by bit-pirate** [comment]
Ha, I actually confused this a bit. The teleop rapp running on the robot is actually very light-weight - it just needs to listen to velocity commands. One can see this as the output part of the whole teleop application. The overview given above is focusing on the input part - keyboard, joystick, Android app, Qt app.

PR #229 adds the implementation of the teleop rapp, which is quite simple, since most of it is actually implemented by the capabilities it depends on.

On the other hand, it would still be nice to have a general implementation for keyboard and joystick inputs. Also, we might need to implement a generic joystick app, which enables joystick teleop, when the joystick is connected to the robot.

**Comment by jihoonl** [comment]
My brain is full of other stuffs at the moment. I will follow up this after the demo.

**Comment by jihoonl** [comment]
After discussion, We have agreeed to have `Teleop` and `VideoTeleop`. and Teleop rapp will start `joy` node for now. Then we will split JoyTeleop later when we see necessity.
