### ISSUE TITLE
Check Ken's app finder

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#2]
Check how he hunts apps.

**Comment by stonier** [comment]
I like ken's - he use a yaml with an array of apps defined. This lets you quickly comment out an app while testing/developing. Source directories dont let you do that (unless you use a blacklist maybe).

For searching any app, icon, launch reference is designated by a package-filename pair. 

He just trawls every dir in `package` looking for `filename`.
