### ISSUE TITLE
[question] Specifying arguments to rapp launch files:

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_app_platform#206]
Can I do either of the following?
- Run an app on a remote concert client with a specific parameter to its launch file
- Supply a parameter to the rapp launch file in the .rapp file

**Comment by stonier** [comment]
> Run an app on a remote concert client with a specific parameter to its launch file

I've been wanting to do this recently as well, see #170 and some discussion in #139. I have enabled remappings in the [start app](https://github.com/robotics-in-concert/rocon_msgs/blob/hydro-devel/rocon_app_manager_msgs/srv/StartApp.srv) and parameters in the interactions, but not yet parameters in the rapps. 

> Supply a parameter to the rapp launch file in the .rapp file

Can't figure out how this might work. Why would putting it in the `.rapp` file be different to putting it in the launcher directly?

**Comment by stonier** [comment]
What's your use case? I can bump up the priority on this.

**Comment by stonier** [comment]
Let's continue the discussion at #170.
