### ISSUE TITLE
[rocon_app_utilities] Extend dependency checker docs

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#209]
Dependency checker's `check_missing_rapp_dependencies()` does not return the reason, why a specific rapp cannot be installed (https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_utilities/src/rocon_app_utilities/dependencies.py#L54-L83).

For debugging purpose it would be great to know, which dependencies are missing.

**Comment by bit-pirate** [comment]
Taking a closer look, I realised that the missing dependencies are indeed stored and returned. Only the doc is missing this. Should be added.

**Comment by dirk-thomas** [comment]
I am not sure what should be added here. Currently the methods doc block mentions that the return value is a tuple with three values (https://github.com/esteve/rocon_app_platform/blob/remote_index/rocon_app_utilities/src/rocon_app_utilities/dependencies.py#L54).

I just added some more details though: https://github.com/esteve/rocon_app_platform/commit/6a393ceb4869c56c9e7844d42f91fee175552a3f

If you could describe a bit more detailed what you think should be added I will do so.

**Comment by bit-pirate** [comment]
What I basically missed, was that those dics did not only contain the names of the rapps. Your newly added comments (https://github.com/esteve/rocon_app_platform/commit/6a393ceb4869c56c9e7844d42f91fee175552a3f) make this clear. Thx!
