### ISSUE TITLE
Upgrades for conductor v2

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#215]
@bit-pirate : a pseudo pull request for you!

See a compare of the diffs here
- rocon_msgs: https://github.com/robotics-in-concert/rocon_msgs/compare/8c28c542394808ed07e1bc66bbd13c40c592c1a9...6d6ff836d22c08bdd576d09e3812ffb4ee178cb6
- rocon_app_platform: https://github.com/robotics-in-concert/rocon_app_platform/compare/6a393ceb4869c56c9e7844d42f91fee175552a3f...c1ba0f386102cd022389e1cb2ce5922b32d750b0

Close this if you're happy.

**Comment by bit-pirate** [comment]
My tests were successful as well. Closing this now - re-open, if new issues are discovered.
