### ISSUE TITLE
Updating the rapp index

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#216]
There are some differences when it comes to how changes in the workspace impact the available list of rapps:
- adding/removing repos immediately impacts the index
- adding src rapps requires a `rocon_app update`
- removing src rapps turns them invalid, because rapp resources cannot be found any more, e.g. icon, launcher etc. After a `rocon_app update` they are completely removed

Cannot test deb rapps, since we haven't released any using the export function in the `package.xml`.

Suggestions:
- Radical change: don't index or always update the index, when executing `rocon_app list` (in which case keeping an index is not really useful any more)
- Alternatives:
  - If rapp is invalid, because of missing resources, do an update to discover completely remove rapps

What's your stand on this @dirk-thomas ?

**Comment by bit-pirate** [comment]
Reminder for myself:
We had the situation today, that rapps, which had been freshly added to the workspace weren't picked up by the rapp manager. However, I couldn't reproduce that behaviour. Post here, if this happens again.

**Comment by dirk-thomas** [comment]
Since the index does currently not provide much of an advantage (since the archive needs to be unpacked to satisfy further API which returns absolute paths to resources) I would suggest to just skip the indexing part for local folders. Then it is always up-to-date. I can do that if we agree on the approach?

**Comment by stonier** [comment]
Dropping as it's not a priority right now....revisit this if it does become a priority in future.
