### ISSUE TITLE
Reconstruct launchers for the rapp manager

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#222]
- [x] No more public/private
- [x] Focus on standalone/multimaster implementations (i.e. no gateway vs gateway)
- [x] Scale up args to enable/disable modules (e.g. zeroconf, caps)
- [x] Specialisation of multimaster for concert client

**Comment by bit-pirate** [comment]
Great work! New launchers look way better.

PS: https://github.com/robotics-in-concert/rocon_app_platform/commit/dda2d980b27d0461b4923cc81a7e3073a9e8375a#commitcomment-6190799

**Comment by bit-pirate** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/blob/indigo/rocon_app_manager/launch/standalone.launch#L16

Misses the debug arg.

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/blob/indigo/rocon_app_manager/launch/includes/_capabilities.xml#L6

describes why debug arg is missed.
