### ISSUE TITLE
Redefine teleop (virtual) rapp

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#224]
Currently the teleop rapp defines both a velocity control and camera feedback interface.

I propose to split this up into `Teleop` - velocity control only - and `VideoTeleop` - velocity control plus video/camera feedback.

Thoughts?

This is related to #199.

**Comment by stonier** [comment]
Sounds good - do you want to do it before or after the demo though?

**Comment by bit-pirate** [comment]
After will be fine. No need to rush this.

**Comment by jihoonl** [comment]
:100:

**Comment by jihoonl** [comment]
Teleop/Video Rapp has been merged with https://github.com/robotics-in-concert/rocon_app_platform/pull/250
