### ISSUE TITLE
[app utilities] Inheriting rapp resources does not work

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#231]
In my case the virtual rapp `rocon_apps/teleop` contains and specifies the icon and interface and the rapps inheriting from it don't. This leads to this error:

```
== Invalid Rapp List == 
  turtlebot_core_apps/teleop : invalid rapp - joystick.png does not exist
  rocon_apps/robot_teleop : invalid rapp - joystick.png does not exist
```

as well as

```
== Invalid Rapp List == 
  turtlebot_core_apps/teleop : invalid rapp - teleop.interface does not exist
  rocon_apps/robot_teleop : invalid rapp - teleop.interface does not exist
```

Looks like resource inheritance does not work with relative paths specified (just `joystick.png` and `teleop.interface`). Changing to a ROS resource identifier (`rocon_apps/joystick.png`) makes it work again.

**Comment by jihoonl** [comment]
Fixed by #252
