### ISSUE TITLE
Rapp manager does not reset its state when stopping rapp failed

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#234]
Had a situation here, where stopping a rapp failed (related with capabilities: #https://github.com/robotics-in-concert/rocon_app_platform/issues/233). The service response returns the error, but the status of the rapp manager still says it's running the rapp.

**Comment by stonier** [comment]
No updates for a long time, reopen if necessary, but not essential right now.
