### ISSUE TITLE
Tests failing on buildfarm

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#236]
Due to import error:

```
 nose.failure.Failure.runTest
 Error Details
No module named rocon_ebnf.rule_parser
```

http://jenkins.ros.org/job/devel-indigo-rocon_app_platform/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/37/testReport/

**Comment by stonier** [comment]
[Jenkins console report](http://jenkins.ros.org/job/devel-indigo-rocon_app_platform/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/37/console).

**Comment by stonier** [comment]
Missing dependency on `rocon_ebnf` inside `rocon_uri`. This was already fixed in https://github.com/robotics-in-concert/rocon_tools/commit/2133c7032607d8e82c9f7ea7e7063879acbf2566 May 10, but hasn't been released yet. This should go away on the next deb release since this build used the old debs.
