### ISSUE TITLE
Check if rospack cache recrawl is still required for rapp installation

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#241]
Currently the rapp installation process (https://github.com/robotics-in-concert/rocon_app_platform/issues/211) uses a `rospack profile` call to manually trigger the update of rospack's cache: https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp.py#L94-L97

With the updates in nodelet_core (https://github.com/ros/nodelet_core/pull/20) in place this might not be needed any more. There is also a related change in pluginlib (https://github.com/ros/pluginlib/issues/23). For indigo all these changes have already been released. However, I'm not sure if this manual cache update can safely be dropped for hydro as well. Test!

**Comment by stonier** [comment]
Dropping this as we are no longer supporting hydro.
