### ISSUE TITLE
Documentation about rapp installation and remote indexer

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#249]
Need some documentation to use rapp installer and remote indexer. 

@dirk-thomas, @bit-pirate  Could you provide or point to the right person?

**Comment by jihoonl** [comment]
Related Issues : #189, #190, #191, #197

**Comment by jihoonl** [comment]
@dirk-thomas @bit-pirate bump 

I need these information soon for further development...

**Comment by dirk-thomas** [comment]
I don't know about any further documentation beside:
- the discussion on the pull requests (referenced above),
- the API documentation (e.g. https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_utilities/src/rocon_app_utilities/indexer.py) in the code and
- the tests actually using the API (https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_utilities/tests/test_rapp_repositories.py).

**Comment by bit-pirate** [comment]
> Need some documentation to use rapp installer and remote indexer.

@jihoonl are you looking for something like a ROS tutorial on how to set up and use rapp indices as well as the auto-install function?

@jihoonl the rocon_app_utilities hasn't been released yet. Is there a schedule for this? Once we release it, we should make sure the existing API documentation is parsed correctly (Sphinx).

**Comment by jihoonl** [comment]
> are you looking for something like a ROS tutorial on how to set up and use rapp indices as well as the auto-install function?

Exactly. I need some starter's guideline how to use. Need information to start to make remote rapp repositories to collaborate with Cento.

> the rocon_app_utilities hasn't been released yet. Is there a schedule for this? Once we release it, we should make sure the existing API documentation is parsed correctly (Sphinx).

`rocon_app_utilities` package is already released in indigo and document is parsed. http://docs.ros.org/indigo/api/rocon_app_utilities/html/

**Comment by bit-pirate** [comment]
> Exactly. I need some starter's guideline how to use. Need information to start to make remote rapp repositories to collaborate with Cento.

I'll try to put something together this week. @dirk-thomas once I have the first draft up on the wiki, could you do a review to make sure I got everything right?

**Comment by bit-pirate** [comment]
I have added tutorials for using the indexer and installer.
- http://wiki.ros.org/rocon_app_utilities/Tutorials/indigo/Create%20a%20Rapp%20Index
- http://wiki.ros.org/rocon_app_utilities/Tutorials/indigo/Install%20Rapps

@jihoonl and @dirk-thomas please review you them and post here what's missing or should be fixed.

**Comment by bit-pirate** [comment]
Identified an issue with the index builder #253. Also need to update kobuki_apps to use relative paths for resources: https://github.com/yujinrobot/kobuki/issues/342

**Comment by dirk-thomas** [comment]
In the first tutorial (http://wiki.ros.org/rocon_app_utilities/Tutorials/indigo/Create%20a%20Rapp%20Index) the link to the next one is broken. Beside that it looks good to me.

**Comment by bit-pirate** [comment]
Just fixed that. I would consider this issues as solved. @jihoonl please close it, if you agree.

**Comment by jihoonl** [comment]
The doc looks good to me too. I will reopen if anything need to be updated.
