### ISSUE TITLE
Depending on yujin_ocs in rocon_apps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#262]
There has been a dependency introduced in rocon_apps on yujin_ocs (velocity smoother) via the robot teleop app.

While it does make sense to have the velocity smoother for a teleop app, this repo should not have a dependency on yujin_ocs. Perhaps this 'implementation' should be moved elsewhere and just a very simple implementation used as the default (for tutorials perhaps?).

**Comment by jihoonl** [comment]
How about `yocs_rapps` in yujin_ocs package? to keep the sharable implementation rapps.

**Comment by stonier** [comment]
+1

**Comment by bit-pirate** [comment]
+1
