### ISSUE TITLE
Env-hook based configuration 

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#267]
There are lots of args in [standalone.launch](https://github.com/robotics-in-concert/rocon_app_platform/blob/indigo/rocon_app_manager/launch/standalone.launch) and [concert_client.launch](https://github.com/robotics-in-concert/rocon_app_platform/blob/indigo/rocon_app_manager/launch/concert_client.launch) to utilise rapp manager.  Here is a proposal to create configurable env-hooks. These are the list of configurations which I frequently customise to use in waiterbot and turtlebot. 

**Proposed envs**
- ROBOT_NAME
- ROBOT_DESCRIPTION
- ROBOT_TYPE
- RAPP_PACKAGE_WHITELIST
- RAPP_PACKAGE_BLACKLIST
- ROBOT_UNIQUE_NAME
- CONCERT_WHITELIST
- CAPABILITIES
- CAPABILITIES_PARAMETERS
- CAPABILITIES_PACKAGE_WHITELIST
- CAPABILITIES_BLACKLIST
- INTERACTIONS
- INTERACTIONS_LIST
- INTERACTION_ROSBRIDGE_ADDRESS
- INTERACTION_ROSBRIDGE_PORT

**Available args in rapp manager**

Capabilities
- capabilities
- capabilities_parameters
- capabilities_blacklist
- capabilities_nodelet_manager_name
- capabilities_package_whitelist
- capabilities_server_name

Rapp manager
- auto_rapp_installation
- auto_start_rapp
- rapp_package_whitelist
- rapp_package_blacklist
- robot_name
- robot_type
- robot_icon
- screen
- simulation
- robot_descrtiption

Interactions
- interactions
- interactions_list
- rosbridge_address
- rosbridge_port

Concert Client.launch
- concert_whitelist
- robot_unique_name
- local_machine_only
- concert_whatch_period
- firewall

**Comment by jihoonl** [comment]
@stonier, @mikeferguson, @tfoote 

![untitled drawing](https://cloud.githubusercontent.com/assets/1556736/5584814/3a5a057c-90dc-11e4-99c5-813376a76a24.png)

I was expecting this kind of environment configuration to tune the common env variables for turtlebot. But actually it has potential conflicts and gave me these questions.
- What if a user wants to keep two robot implmentation(pr2_bringup, and turtlebot_bringup) in one PC? 
- What if both pr2_bringup and turtlebot_bringup attempts to overwrite the same environment variables(ROBOT_NAME, ROBOT_TYPE, RAPP_PACKAGE_WHITELIST, and etc)?

Any suggestions?

**Comment by tfoote** [comment]
Can you clarify what conflicts you're getting? Are you trying to launch 2 robots at once? You should be able to set the environment variables within a scope.

**Comment by jihoonl** [comment]
It wouldn't have any problem if all robots are running in different workspace. The conflict arises when it comes to debs.

![untitled drawing 2](https://cloud.githubusercontent.com/assets/1556736/5585574/195b53b8-90f4-11e4-8ff9-b3cd19f84c9e.png)

Assumes that user uses rocon_app_manager, turtlebot_bringup, and pr2_bringup(or another robot) from debs. Then, the default value for ROBOT_NAME and ROBOT_TYPE would be set by env-hook priority set by each package. So the conflict happens when all the packages are in the same scope.

Or is there anyway to separate the scope even though all package are in debs ?

**Comment by tfoote** [comment]
Yes, you can't be exporting these values in env-hooks of a package. Exported values must not conflict and be used as a discovery mechanism not a configuration mechanism. 

you should have an entry point for each "robot" which sets the appropriate environmet varialbes for the desired robot.

**Comment by stonier** [comment]
I rather like exporting variables via env-hooks. It's a great way of getting default settings into your workspace without requiring...anything extra. This requires the assumption they be unique though....hence the prefixing.

**Comment by jihoonl** [comment]
@mikeferguson any thoughts?

**Comment by stonier** [comment]
I've much reduced the arg list in the gopher branch...and we're quite fine with setting these via a constructed launcher outside. And it's there we have robot specific environment variables that get dragged in. 

I'd rather keep these launchers clean with only one method for pulling in parameterisations - the ros args.
