### ISSUE TITLE
Rapp package blacklist doesn't make sense

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#278]
I thought this was originally a rapp blacklist, so you could blacklist individual rapps from inside a package that was loaded via the whitelist.

Right now it doesn't make sense and as a result its completely redundant/useless. The only time you'd have it in the blacklist is when you have it in the whitelist. In which case you should just take it out of both lists.

**Comment by jihoonl** [comment]
I thought it was to provide two ways to use rapps.

 whitelisted rapp package or All rapp packages except blacklisted rapp packages.

**Comment by stonier** [comment]
Aight...I really am having a slow day :/

Been ages since I used that functionality. I'm sure I've implemented something like the above somewhere though.
