### ISSUE TITLE
Not found rapp

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#28]
app_manager crashes if rapps file contains invalid rapp, it crashes app manager.

It should warn the rapp description is invalid and continue to run.

**Comment by stonier** [comment]
- [x] handle the case when the rapp is not found in the rapp lists (the .rapp file not found)
- [x] handle the case when the interface file is not found
- [x] handle the case when the launch file is not found

In all cases, it should 1) ignore the app, 2) provide a warning and 3) proceed to the next app in the rapp list.

**Comment by stonier** [comment]
10497e9f8b61239ec26d2a9e0478fecfc9b18a15
