### ISSUE TITLE
Missing launch files

### ISSUE THREAD

**Issue by mistoll** [robotics-in-concert/rocon_app_platform#282]
In paired.concert two launch files are mentioned
- paired_public.launch
- paired_private.launch

those do not exist in the package.

**Comment by jihoonl** [comment]
What version are you using? and where dose paired.concert come from?

**Comment by mistoll** [comment]
Im using the indigo branch (latest)
paired.concert is here:
https://github.com/robotics-in-concert/rocon_app_platform/blob/indigo/rocon_app_manager/concert/paired.concert

**Comment by jihoonl** [comment]
I see thanks @mistoll. It is legacy code from hydro. I am removing it now
