### ISSUE TITLE
improve points for interface 

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#3]
The old interface required type of topic. No need for new gateway model.

**Comment by stonier** [comment]
You mean like the std_msgs/String type? It's curious - why does master sync need that? Also why does rostopic pub also need that when rosservice doesn't?

**Comment by jihoonl** [comment]
With quick investigation, master sync actually does not use the type. It just grabs topic type using rosmaster api. So we may remove it.

rostopic pub needs topic type because rosmaster need to know what it is if a topic does not registered in rosmaster yet.
rosservice does not need it because there always be service server. rosservice command line is just a client.

**Comment by stonier** [comment]
So logical, thanks for making me feel like a newb. One needs that every now and then ;)
