### ISSUE TITLE
[gopher] Flip rules for subscribers

### ISSUE THREAD

**Issue by asmodehn** [robotics-in-concert/rocon_app_platform#308]
Added this for the automatic door integration to work by flipping subscribers from inside a rapp : 
https://github.com/robotics-in-concert/rocon_app_platform/commit/f079f7858d7b206b3e22c164712e32f1948f3f16

Not sure if it is the best place to do it, and how the public.interface relate to that at the moment in the gopher branch...
@stonier : In need of some review...

**Comment by stonier** [comment]
Ok...looks like I threw that in there to get started with publishers because that's all we were using.

Now is the time to add subscribers, services, action clients and action servers.

**Comment by stonier** [comment]
Just adding subscribers, and just for the concert namespace (not the app namespace) isn't sufficient.
