### ISSUE TITLE
Interface file api

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#5]
Old interface file :

published_topics :
topic_name:topic_type

subscribed_topics:
same

New interface file :

publisher:
[topic_name ....]
subscriber:
[topic_name...]
service:
[service_name...]

**Comment by jihoonl** [comment]
How should we deal with '/' in front of topic names

option : 
1. automatically add or remove '/' when it is being parsed.
2. force user to put '/' for topics.

**Comment by stonier** [comment]
This is old and has been dealt with appropriately to work the same as the way roslaunchers work.
