### ISSUE TITLE
Sending parameters to pairing clients

### ISSUE THREAD

**Issue by corot** [robotics-in-concert/rocon_app_platform#58]
Android apps had harcoded topics names (only the app namespace is dynamic).

New app manager should fix this somehow, for example defining topic names on .rapp file.

**Comment by stonier** [comment]
Yeah, it was in the old app manager actually, but not heavily used (or even supported?).

I'd like to configure the .rapp files to additionally send along params to the app. These can then be picked up by the android app to configure itself (of which naming topics is a part).

**Comment by bit-pirate** [comment]
@stonier What is the status on this? I remember working being done for this on the Android app side.

**Comment by stonier** [comment]
The merge of concert and pairing apps should enable this, but I need to test and verify it to understand what is there.

**Comment by stonier** [comment]
Superceded by #170.
