### ISSUE TITLE
Handling installed and runnable apps

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#67]
The app manager currently only offers one `list_apps` services.
Now, that we start to differentiate between installed and runnable apps (see #66), we probably need to set up an addtional list and service for either the runnable or the installed apps.

Any preferences?

**Comment by stonier** [comment]
Probably just cache it in the home directory like the old app manager did. Haven't implemented the actual installable feature yet though.

**Comment by bit-pirate** [comment]
Internally there is already the differentiation of pre-installed and running app(s).

For not breaking compatibility with the rest of the rocon app platform we could only make the runnable apps appear in the `list_apps` services and rostopic. However, for semantic reasons I would prefer topics and services such as `list_runnable_apps` and `list_installed_apps`.

**Comment by bit-pirate** [comment]
I implemented my preferred solution in a first draft. However, this can be easily changed, if wanted.

**Comment by stonier** [comment]
Hmm...changing the list apps publisher will break compatibility with the rest of the rocon app platform (I can't remember who is using the publisher and who the service, but potentially both or either android robot_remocon and conductor components will fail).

Note: AppList.msg is about running_apps, not runnable_apps. Just checking if there is a confusion there.

```
App[] available_apps
App[] running_apps
```

Question: do we need to differentiate between installed and runnable? Or in the current msg terminology, 'available'. Available apps would just be the list of all possible apps filtered by the capability requirements. Do we need to expose the unfiltered list to anybody?

If we don't have any users of an unfiltered list, then let's not make that publisher - it's just noise (i.e. list_installed_apps).

**Comment by bit-pirate** [comment]
The default service and rostopic names for retrieving available apps is
just labelled `~/list_apps` and `~/app_list`. So by that it's hard
to tell what kind of apps you get when calling that service/listening to
that topic.

I want to provide a `~/installed_apps` service/topic to allow
introspection - mostly for developers. This will help them to identify
their problems will setting up their own apps. E.g. is the app itself
wrongly configured or are just the capabilities not available.

Remember that I prun the list of runnable apps, hence the unsupported apps
would just disappear. Well, I have warning at startup for unsupported apps
due to missing capabilities. Do you think that warning at startup would
suffice?

2013/10/11 Daniel Stonier notifications@github.com

> Hmm...changing the list apps publisher will break compatibility with the
> rest of the rocon app platform (I can't remember who is using the publisher
> and who the service, but potentially both or either android robot_remocon
> and conductor components will fail).
> 
> Note: AppList.msg is about running_apps, not runnable_apps. Just checking
> if there is a confusion there.
> 
> App[] available_apps
> App[] running_apps
> 
> Question: do we need to differentiate between installed and runnable? Or
> in the current msg terminology, 'available'. Available apps would just be
> the list of all possible apps filtered by the capability requirements. Do
> we need to expose the unfiltered list to anybody?
> 
> If we don't have any users of an unfiltered list, then let's not make that
> publisher (i.e. list_installed_apps).
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/robotics-in-concert/rocon_app_platform/issues/67#issuecomment-26120562
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by bit-pirate** [comment]
For now I made both the list of installed and runnable apps available. For backwards compatibility the runnable apps are accessable using the old service name `/list_apps` and the topic name `/apps_list`.

Once #112 is being worked on, we should revise this and decide on breaking backwards compatibility for the sake of better semantics.

**Comment by bit-pirate** [comment]
Result from #112: We will stick with `/list_apps`, but the service will respond with the categories `available_apps`, `running_apps` and `installable_apps`. The development of the rapp repo will implement the later.

Considering this done.
