### ISSUE TITLE
Shutdown app manager, if init fails

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#68]
Would like to shut down the app manager node if init fails.
Any objections (@stonier @jihoonl)?

**Comment by stonier** [comment]
Questions
- Under what conditions does it fail?
- Why do you want to shut down the node?

**Comment by bit-pirate** [comment]
After reviewing this, I don't see the necessity any more to shut it down. I'll reopen this issues, if I can come up with a good use case.
