### ISSUE TITLE
Speed up loading of rapps

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#71]
Currently loading 12 rapps takes over 5 seconds. Can this be done faster?

**Comment by stonier** [comment]
You mean on startup when it scans the rapps?

That's a curiously long time just to read a 10 line text file...

**Comment by bit-pirate** [comment]
> You mean on startup when it scans the rapps?

Yes.

> That's a curiously long time just to read a 10 line text file...

Indeed.
