### ISSUE TITLE
pass gateway base name and application namespace as args to rapp

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_app_platform#73]
I don't see any harm in passing this information, and I can set tf_prefix for the rapp appropriately through a launch file argument.

**Comment by stonier** [comment]
We ran into a problem where passing the arg through the include tag generated by the app manager will raise an exception if the app launcher doesn't set an arg variable for that. See roslaunch code here:

https://github.com/ros/ros_comm/blob/hydro-devel/tools/roslaunch/src/roslaunch/loader.py#L126

**Comment by stonier** [comment]
Another way we could solve this is by:
-  When we construct each Rapp():
  - Parse the rapp launcher looking for global arg's
  - For each 'standard' arg found, we flag it in the Rapp class
- When we start the rapp, we modify the process for creating the start launcher
  - For each flagged arg, we write a line that pass in that arg to the include in the start launcher
  - For each non-flagged arg, we do nothing.

I can't see any negatives to doing this, and it lets them keep the current roslaunch check for defined args. What do you think @piyushk?

**Comment by piyushk** [comment]
@stonier I agree.

I am working on this now, as it is required for our simulated concert demo. I only hacked in a solution earlier.
