### ISSUE TITLE
How to remap topics using roslaunch

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#75]
I started looking into doing topic remapping - using roslaunch because that's how the app manager launches apps.

However, at this point I have no idea how to inject the new topic names. As far as I can tell remapping is done on the node level not roslaunch.

Need to find a convenient way how to do this.

@stonier @wjwwood any ideas?

**Comment by wjwwood** [comment]
To get a better idea of what the use case is, can you give an example of the scenario and what your would like to rename and why?

**Comment by stonier** [comment]
ditto, bit unclear on your situation as well.

**Comment by bit-pirate** [comment]
I have to remap certain topics of an app to the topic names given by the capability specification. For example: An app publishes velocity commands on `/my_app/commands/velocity`, and the cap provider is listenening to `/cmd_vel`.

The app manager starts apps via roslaunch using it's Python API. So now I need to find ways to do those kind of remappings when starting apps - preferably using the same API.

My first look at roslaunch''s  Python API did not give me a clear idea about how this can be achieved. I couldn't find any methods allowing to set remappings.

To correctly understanding roslaunch, is it true, that roslaunch only parses the information inside the `<remap/>` tags and passes them on to rosrun to start the nodes, e.g. `rosrun my_pkg my_node from_topic:=to_topic`?

**Comment by wjwwood** [comment]
Maybe this is a naive question, but why doesn't the interface, provider, and app developer all use the same topic names?

For how to actually do the remapping, I'm not familiar enough with the internals of roslaunch to know how to effect that change. This is probably something I will have to do in the future to fully support semantic interfaces ability to remap things.

**Comment by bit-pirate** [comment]
> Maybe this is a naive question, but why doesn't the interface, provider, and app developer all use the same topic names?

I agree that would be a simple solution, but we believe that will be difficult to enforce. The ROS systems out there run on different hardware, with different sets of programs (caps & apps), configured/programmed by different developers. Those developers might decide to/are forced to adhere to certain style/standard for there robots in terms of naming.

Ourselves (Yujin devs) might be a good/bad example. We already diverged from the old unofficial ROS standards, such as `/cmd_vel` and `/odom` for good reasons (we think). These situations are likely to happen more often than less. This is also the reason, I'd like to allow non-standard topic names for the capability specs. E.g. capabilty provider defines its own name for `/cmd_vel` and the app as well. This would give a lot of flexibility and freedom to the both the apps and caps developers (and the discussions about standard topic names will be reduced). I believe once we find ways to do the remappings that should not be too hard to implement.

**Comment by wjwwood** [comment]
> Ourselves (Yujin devs) might be a good/bad example. We already diverged from the old unofficial ROS standards, such as /cmd_vel and /odom for good reasons (we think).

I think part of the point of the capabilities is to decide on a best practice and make an interface that we can all agree on is the best sane default.

> I believe once we find ways to do the remappings that should not be too hard to implement.

Sure, I'm not saying we shouldn't support it (we will have to have this ability to implement semantic capabilities), but I just don't want to use it as a crutch for letting everyone do different things. I think we should really encourage people (robot and app developers) to converge on naming.

The `/odom` I used was out of habit, we still need to go through the process of drafting real standard interfaces and bringing the community in on those, maybe even doing reps for some of them.

**Comment by bit-pirate** [comment]
> Sure, I'm not saying we shouldn't support it (we will have to have this ability to implement semantic capabilities), but I just don't want to use it as a crutch for letting everyone do different things. I think we should really encourage people (robot and app developers) to converge on naming.

I'm not sure we have to. ROS is create at being so flexible and giving developers a lot of freedom how to do things. The capabilities would give us the chance to forget about topic namings. Do you see potential problems/risk in that?

**Comment by wjwwood** [comment]
It's not about having the freedom to do it, it's about readability and comprehension for me. Looking at a system which has a clearly defined interface which says `foo`, a robot which is actually providing `bar`, and an app which is looking for `baz` could get out of hand quite quickly.

To reiterate, I think it is vital for us to have this flexibility, but we should still strive to simplify things by coming to a consensus on the common cases.

It's not a perfect analogy, but we have done something similar with Message types where, it is flexible enough such that anyone could make up new message types, and two different message types can be converted between each other if needed, but we benefit greatly from having a common set of messages which cover 80% of the cases.

It's all a bit philosophical and sort of moot since we need the feature regardless of our recommendation.

**Comment by bit-pirate** [comment]
Agreed. I think, those kinds of standards need further discussion, at some point with the ROS community. Once we have first full implementation of apps with caps working, we should do another hangout - maybe including few more who have already some experience with capabilities, e.g. fergs.

So back to the topic, how can we get this remapping happening? :-)

**Comment by wjwwood** [comment]
No idea. I haven't had a chance to look into it.

**Comment by stonier** [comment]
rocon_app_manager has some [example code](https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro/rocon_app_manager/src/rocon_app_manager/rapp.py#L217). In particular, note the following lines:

```
for N in self._launch.config.nodes:
    N.remap_args.append((t, remapped_name))
```

Probably need to do some experimenting with that...

**Comment by bit-pirate** [comment]
After wandering a while through roslaunch's forest of classes and methods, I found that one as well. I have a working implementation for remappings looking similar to what you have posted. There are some caveats, but in general it looks like a feasible solution. I'll upload the code soon.

**Comment by bit-pirate** [comment]
Here is the code: https://github.com/robotics-in-concert/rocon_app_platform/blob/capabilities_integration/rocon_app_manager/src/rocon_app_manager/rapp.py#L281

I'm considering this done. If there are issues with the current implementation or a better way to implement this is found, please open new issues (or reopen this one).

**Comment by stonier** [comment]
Just make sure you lose the debug prints before pull requesting, otherwise looks ok.
