### ISSUE TITLE
app manager throws exception, when trying to stop a not running app

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#80]
Add a corresponding check.

**Comment by stonier** [comment]
What conditions led to this?

When trying to stop an app that isn't running I get:

```
# Chirp auto-stops here.
[INFO] [WallTime: 1382200540.652527] App Manager : stopping rapp : rocon_apps/chirp
[INFO] [WallTime: 1382200540.653967] App Manager : stopped app [rocon_apps/chirp]
# Sent a stop_app request here.
[WARN] [WallTime: 1382200548.890589] App Manager : received a request to stop a rapp, but no rapp found running.
```

**Comment by stonier** [comment]
Closing this, reopen it with log information or reproducable instructions if you see it again.

**Comment by bit-pirate** [comment]
Sorry for the late reply. Just checked this again and I found the cause of this being an addition of mine in the capabilities_integration branch. I fixed it there.
