### ISSUE TITLE
Paired master allowed two android access into one robot

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#84]
Sometimes it happens.

**Comment by bit-pirate** [comment]
Is this still happening @jihoonl? If not, let's close this issue and re-open it, in case this error occurs again in the future.

**Comment by stonier** [comment]
Yes, call me immediately if you see it happen.

I imagine this may have been from some indeterminate state that crashes on either side affected. In that case, we should make it robust anyway, but would need to see it or reproduce it.
