### ISSUE TITLE
self locked paired master

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#85]
Paired master sometimes does not allow any connection from tablet.

**Comment by stonier** [comment]
Again, error messages when you can catch them in the future would be useful.

**Comment by bit-pirate** [comment]
Is this still happening @jihoonl? If not, let's close this issue and re-open it, in case this error occurs again in the future.

**Comment by jihoonl** [comment]
Haven't seen yet.

**Comment by bit-pirate** [comment]
> Haven't seen yet.

OK, closing this now. Reopen when you see it again.
