### ISSUE TITLE
Re-iterate on how to align concert, rapp and capability remappings

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#98]
Personal reminder. Will add details later.

**Comment by stonier** [comment]
Personal reminder for me - I'm starting to lean fondly towards the slightly fugly relays for the few use cases where it's pertinent. I think we can do this in a transparent way when needed, but it's also necessary for alot of other cases.

**Comment by bit-pirate** [comment]
We also need to make sure that remapping works for manually starting app involving custom remappings.

**Comment by bit-pirate** [comment]
Brief summary of the issue:
With the new system the capabilities dictate the topic names (https://github.com/osrf/capabilities/pull/30). That means rapps have to adhere to them, what conflicts with the old style, in which we remapped rapp topics according to the needs of the concert.

The current solution we are investigating is using topic relays in the rapps for concert topics.

**Comment by stonier** [comment]
As @bit-pirate mentioned, we use relays to make do here.
